//
// BatchJob.cs
// Author: Jerry Fu <jerry@glasslabgames.org>
// 2014 - 8 - 5
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace GlassLab.Batch
{
  public class BatchJob
  {
    private Action m_job;

    public bool IsComplete { get; internal set; }

    public string Name { get; private set; }

    internal float ExecutionTime;

    public BatchJob(Action job, string name)
    {
      this.m_job = job;
      this.Name = name;
    }

    // Internal because this should only be done and managed through the batch manager
    internal void Do()
    {
      if (!IsComplete)
      {
        float startTime = Time.realtimeSinceStartup;
        m_job();
        IsComplete = true;
        ExecutionTime = Time.realtimeSinceStartup - startTime;
        Debug.Log("Completed '"+Name+"' in "+(ExecutionTime*1000f)+"ms");
      }
      else
      {
        throw new Exception("Tried to do job that's already completed");
      }
    }
  }
}